# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: false
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="false"
    - python: 3.7
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py37" COVERAGE="false"
    - python: 3.8
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py38" COVERAGE="false"

    - env: DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.8" COVERAGE="true"

install:
  - cat setup.cfg
  - source tests/travis_install.sh
  - pip install .[dev]
# before_script:
#   - git config --global user.email "you@example.com"
#   - git config --global user.name "Your Name"
script:
  - tox
#   - |
#     if [[ "$COVERAGE" == "true" ]]; then
#       pre-commit install
#       pre-commit run --all-files
#     fi

# notification settings
notifications:
    email:
        recipients:
            - consistentbayes@gmail.com
        on_success: change
        on_failure: always

# whitelist
branches:
    only:
        - master
        - develop

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
